import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { getDb } from "@/db";
import {
  activities,
  activityLogs,
  analyticsDaily,
  analyticsEvents,
  clientFavorites,
  clientPropertyPresentations,
  clients,
  dealProperties,
  deals,
  documentCategories,
  notifications,
  opportunityAttachments,
  owners,
  properties,
  propertyDocuments,
  propertyOwners,
  propertyPhotos,
  proposals,
  reminderSettings,
  sales,
  searchAlerts,
  stages,
  tenantAuditLogs,
  tenantInvites,
  tenantMemberships,
  tenantModules,
  tenantProvisioning,
  tenants,
  tenantSlugHistory,
  users,
  visits,
  whatsappClicks,
} from "@/db/schema";
import { requireAdmin } from "@/lib/access";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET() {
  const user = await requireAdmin();
  const db = getDb();
  const tenantId = user.tenantId;

  const [
    [tenant],
    memberships,
    invites,
    modules,
    provisioning,
    slugHistory,
    reminders,
    propertyRows,
    photoRows,
    ownerRows,
    propertyOwnerRows,
    categoryRows,
    documentRows,
    clientRows,
    stageRows,
    dealRows,
    dealPropertyRows,
    attachmentRows,
    activityRows,
    favoriteRows,
    presentationRows,
    visitRows,
    proposalRows,
    saleRows,
    alertRows,
    notificationRows,
    activityLogRows,
    analyticsEventRows,
    analyticsDailyRows,
    whatsappRows,
    auditRows,
  ] = await Promise.all([
    db.select().from(tenants).where(eq(tenants.id, tenantId)),
    db.select({
      id: tenantMemberships.id,
      userId: users.id,
      name: users.name,
      email: users.email,
      role: tenantMemberships.role,
      status: tenantMemberships.status,
      permissions: tenantMemberships.permissions,
      invitedAt: tenantMemberships.invitedAt,
      activatedAt: tenantMemberships.activatedAt,
      createdAt: tenantMemberships.createdAt,
      updatedAt: tenantMemberships.updatedAt,
    }).from(tenantMemberships).innerJoin(users, eq(users.id, tenantMemberships.userId)).where(eq(tenantMemberships.tenantId, tenantId)),
    db.select({
      id: tenantInvites.id,
      email: tenantInvites.email,
      name: tenantInvites.name,
      role: tenantInvites.role,
      permissions: tenantInvites.permissions,
      expiresAt: tenantInvites.expiresAt,
      acceptedAt: tenantInvites.acceptedAt,
      invitedBy: tenantInvites.invitedBy,
      createdAt: tenantInvites.createdAt,
    }).from(tenantInvites).where(eq(tenantInvites.tenantId, tenantId)),
    db.select().from(tenantModules).where(eq(tenantModules.tenantId, tenantId)),
    db.select().from(tenantProvisioning).where(eq(tenantProvisioning.tenantId, tenantId)),
    db.select().from(tenantSlugHistory).where(eq(tenantSlugHistory.tenantId, tenantId)),
    db.select().from(reminderSettings).where(eq(reminderSettings.tenantId, tenantId)),
    db.select().from(properties).where(eq(properties.tenantId, tenantId)),
    db.select().from(propertyPhotos).where(eq(propertyPhotos.tenantId, tenantId)),
    db.select().from(owners).where(eq(owners.tenantId, tenantId)),
    db.select().from(propertyOwners).where(eq(propertyOwners.tenantId, tenantId)),
    db.select().from(documentCategories).where(eq(documentCategories.tenantId, tenantId)),
    db.select().from(propertyDocuments).where(eq(propertyDocuments.tenantId, tenantId)),
    db.select().from(clients).where(eq(clients.tenantId, tenantId)),
    db.select().from(stages).where(eq(stages.tenantId, tenantId)),
    db.select().from(deals).where(eq(deals.tenantId, tenantId)),
    db.select().from(dealProperties).where(eq(dealProperties.tenantId, tenantId)),
    db.select().from(opportunityAttachments).where(eq(opportunityAttachments.tenantId, tenantId)),
    db.select().from(activities).where(eq(activities.tenantId, tenantId)),
    db.select().from(clientFavorites).where(eq(clientFavorites.tenantId, tenantId)),
    db.select().from(clientPropertyPresentations).where(eq(clientPropertyPresentations.tenantId, tenantId)),
    db.select().from(visits).where(eq(visits.tenantId, tenantId)),
    db.select().from(proposals).where(eq(proposals.tenantId, tenantId)),
    db.select().from(sales).where(eq(sales.tenantId, tenantId)),
    db.select({
      id: searchAlerts.id,
      email: searchAlerts.email,
      filters: searchAlerts.filters,
      confirmedAt: searchAlerts.confirmedAt,
      cancelledAt: searchAlerts.cancelledAt,
      createdAt: searchAlerts.createdAt,
      updatedAt: searchAlerts.updatedAt,
    }).from(searchAlerts).where(eq(searchAlerts.tenantId, tenantId)),
    db.select().from(notifications).where(eq(notifications.tenantId, tenantId)),
    db.select().from(activityLogs).where(eq(activityLogs.tenantId, tenantId)),
    db.select().from(analyticsEvents).where(eq(analyticsEvents.tenantId, tenantId)),
    db.select().from(analyticsDaily).where(eq(analyticsDaily.tenantId, tenantId)),
    db.select().from(whatsappClicks).where(eq(whatsappClicks.tenantId, tenantId)),
    db.select().from(tenantAuditLogs).where(eq(tenantAuditLogs.tenantId, tenantId)),
  ]);

  if (!tenant) return new NextResponse(null, { status: 404 });

  await db.insert(tenantAuditLogs).values({
    tenantId,
    actorUserId: user.id,
    action: "tenant.exported",
    entityType: "tenant",
    entityId: tenantId,
    metadata: { format: "json", requestedBy: user.email },
  });

  const generatedAt = new Date().toISOString();
  const body = {
    schemaVersion: 1,
    generatedAt,
    tenant,
    memberships,
    invites,
    modules,
    provisioning,
    slugHistory,
    reminders,
    properties: propertyRows,
    propertyPhotos: photoRows,
    owners: ownerRows,
    propertyOwners: propertyOwnerRows,
    documentCategories: categoryRows,
    propertyDocuments: documentRows,
    clients: clientRows,
    stages: stageRows,
    deals: dealRows,
    dealProperties: dealPropertyRows,
    opportunityAttachments: attachmentRows,
    activities: activityRows,
    clientFavorites: favoriteRows,
    clientPropertyPresentations: presentationRows,
    visits: visitRows,
    proposals: proposalRows,
    sales: saleRows,
    searchAlerts: alertRows,
    notifications: notificationRows,
    activityLogs: activityLogRows,
    analyticsEvents: analyticsEventRows,
    analyticsDaily: analyticsDailyRows,
    whatsappClicks: whatsappRows,
    tenantAuditLogs: auditRows,
  };
  const date = generatedAt.slice(0, 10);
  return NextResponse.json(body, {
    headers: {
      "Content-Disposition": `attachment; filename="${tenant.slug}-export-${date}.json"`,
      "Cache-Control": "private, no-store",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
