import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getDb } from "@/db";
import { activityLogs, properties } from "@/db/schema";
import { requireUser } from "@/lib/auth";

const input=z.object({code:z.string().min(3).max(30),title:z.string().min(8).max(180),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),type:z.string().min(2),price:z.coerce.number().positive(),city:z.string().min(2),state:z.string().length(2),neighborhood:z.string().min(2),address:z.string().min(5),description:z.string().min(30),bedrooms:z.coerce.number().int().min(0),bathrooms:z.coerce.number().int().min(0),parking:z.coerce.number().int().min(0),area:z.coerce.number().positive()});
async function createProperty(formData:FormData){"use server";const user=await requireUser();const parsed=input.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("Dados inválidos");const p=parsed.data;const db=getDb();const [created]=await db.insert(properties).values({code:p.code,title:p.title,slug:p.slug,type:p.type,priceCents:Math.round(p.price*100),city:p.city,state:p.state.toUpperCase(),neighborhood:p.neighborhood,addressPrivate:p.address,description:p.description,bedrooms:p.bedrooms,bathrooms:p.bathrooms,parkingSpaces:p.parking,privateArea:p.area.toString(),status:"rascunho"}).returning({id:properties.id});await db.insert(activityLogs).values({userId:user.id,entityType:"property",entityId:created.id,action:"create",details:{code:p.code}});revalidatePath("/painel/imoveis");redirect("/painel/imoveis")}
export default function NewPropertyPage(){return <div className="admin-content"><div className="admin-page-title"><div><span>Portfólio</span><h1>Novo imóvel</h1></div></div><form action={createProperty} className="admin-card entity-form"><label>Código interno<input name="code" required placeholder="AV-1050"/></label><label>Título<input name="title" required/></label><label>Slug<input name="slug" required placeholder="apartamento-jardins"/></label><label>Tipo<select name="type"><option>Apartamento</option><option>Casa</option><option>Cobertura</option><option>Studio</option></select></label><label>Valor de venda (R$)<input name="price" type="number" min="1" step="0.01" required/></label><label>Área privativa (m²)<input name="area" type="number" min="1" step="0.01" required/></label><label>Quartos<input name="bedrooms" type="number" min="0" defaultValue="0"/></label><label>Banheiros<input name="bathrooms" type="number" min="0" defaultValue="0"/></label><label>Vagas<input name="parking" type="number" min="0" defaultValue="0"/></label><label>Estado<input name="state" maxLength={2} required defaultValue="SP"/></label><label>Cidade<input name="city" required/></label><label>Bairro<input name="neighborhood" required/></label><label className="wide">Endereço interno completo<input name="address" required/></label><label className="wide">Descrição<textarea name="description" rows={6} required/></label><div className="entity-form-actions"><button className="admin-primary">Salvar como rascunho</button></div></form></div>}
