import { and, asc, desc, eq, ne } from "drizzle-orm";
import { CircleDollarSign, HandCoins, Plus } from "lucide-react";
import { AdminTabs } from "@/components/admin-tabs";
import { EmptyState, PageHeader } from "@/components/admin-ui";
import { AdminDrawerComposer } from "@/components/admin-drawer-composer";
import { ProposalForm, SaleForm } from "@/components/commercial-forms";
import { getDb } from "@/db";
import { clients, deals, properties, proposals, sales } from "@/db/schema";
import { requireModule } from "@/lib/access";
import { formatMoney } from "@/lib/format";
import { updateProposal } from "./actions";

const labels:Record<string,string>={aberta:"Aberta",enviada:"Enviada",em_negociacao:"Em negociação",contraproposta:"Contraproposta",aceita:"Aceita",recusada:"Recusada",expirada:"Expirada"};
export default async function ProposalsPage(){const user=await requireModule("propostas");const db=getDb();const[proposalRows,saleRows,dealRows,propertyRows]=await Promise.all([
 db.select({id:proposals.id,client:clients.name,deal:deals.title,property:properties.title,advertised:proposals.advertisedAmountCents,amount:proposals.amountCents,counter:proposals.counterAmountCents,status:proposals.status,validUntil:proposals.validUntil,createdAt:proposals.createdAt}).from(proposals).innerJoin(deals,and(eq(deals.id,proposals.dealId),eq(deals.tenantId,proposals.tenantId))).innerJoin(clients,and(eq(clients.id,deals.clientId),eq(clients.tenantId,deals.tenantId))).leftJoin(properties,and(eq(properties.id,proposals.propertyId),eq(properties.tenantId,proposals.tenantId))).where(eq(proposals.tenantId,user.tenantId)).orderBy(desc(proposals.createdAt)).limit(100),
 db.select({id:sales.id,client:clients.name,property:properties.title,advertised:sales.advertisedAmountCents,amount:sales.amountCents,commission:sales.commissionCents,soldAt:sales.soldAt}).from(sales).innerJoin(deals,and(eq(deals.id,sales.dealId),eq(deals.tenantId,sales.tenantId))).innerJoin(clients,and(eq(clients.id,deals.clientId),eq(clients.tenantId,deals.tenantId))).innerJoin(properties,and(eq(properties.id,sales.propertyId),eq(properties.tenantId,sales.tenantId))).where(eq(sales.tenantId,user.tenantId)).orderBy(desc(sales.soldAt)).limit(100),
 db.select({id:deals.id,title:deals.title,client:clients.name}).from(deals).innerJoin(clients,and(eq(clients.id,deals.clientId),eq(clients.tenantId,deals.tenantId))).where(eq(deals.tenantId,user.tenantId)).orderBy(asc(clients.name)),
 db.select({id:properties.id,title:properties.title,code:properties.code,price:properties.priceCents}).from(properties).where(and(eq(properties.tenantId,user.tenantId),ne(properties.status,"vendido"))).orderBy(asc(properties.title))
 ]);const dealChoices=dealRows.map(x=>({id:x.id,label:`${x.client} — ${x.title}`}));const propertyChoices=propertyRows.map(x=>({id:x.id,label:`${x.code} — ${x.title} (${formatMoney(x.price)})`}));const proposalChoices=proposalRows.filter(x=>!["aceita","recusada","expirada"].includes(x.status)).map(x=>({id:x.id,label:`${x.client} — ${formatMoney(x.amount)}`}));
 const proposalList=proposalRows.length?<section className="admin-card table-card"><div className="table-toolbar"><div><strong>{proposalRows.length} propostas</strong><span>Histórico preservado</span></div></div><div className="table-scroll"><table><thead><tr><th>Cliente / imóvel</th><th>Valores</th><th>Validade</th><th>Status</th></tr></thead><tbody>{proposalRows.map(p=><tr key={p.id}><td><strong>{p.client}</strong><small>{p.property||p.deal}</small></td><td><strong>{formatMoney(p.amount)}</strong><small>Anunciado {p.advertised?formatMoney(p.advertised):"—"}{p.counter?` · Contraproposta ${formatMoney(p.counter)}`:""}</small></td><td>{p.validUntil?new Intl.DateTimeFormat("pt-BR").format(p.validUntil):"Sem prazo"}</td><td><form action={updateProposal} className="table-inline-form"><input type="hidden" name="id" value={p.id}/><select name="status" defaultValue={p.status} aria-label="Status da proposta">{["enviada","em_negociacao","contraproposta","aceita","recusada","expirada"].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select><button className="admin-button secondary">Atualizar</button></form></td></tr>)}</tbody></table></div></section>:<EmptyState icon={HandCoins} title="Nenhuma proposta registrada" description="Registre a primeira proposta para iniciar o histórico de negociação."/>;
 const saleList=saleRows.length?<section className="admin-card table-card"><div className="table-toolbar"><div><strong>{saleRows.length} vendas concluídas</strong><span>Dados integrados ao dashboard</span></div></div><div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Imóvel</th><th>Valor final</th><th>Comissão</th><th>Data</th></tr></thead><tbody>{saleRows.map(s=><tr key={s.id}><td><strong>{s.client}</strong></td><td>{s.property}</td><td><strong>{formatMoney(s.amount)}</strong><small>Anunciado {s.advertised?formatMoney(s.advertised):"—"}</small></td><td>{formatMoney(s.commission)}</td><td>{new Intl.DateTimeFormat("pt-BR").format(s.soldAt)}</td></tr>)}</tbody></table></div></section>:<EmptyState icon={CircleDollarSign} title="Nenhuma venda concluída" description="As vendas concluídas aparecerão aqui."/>;
 return <div className="admin-content"><PageHeader eyebrow="Negociação" title="Propostas e vendas" description="Registre propostas, contrapropostas e o fechamento de cada negócio." action={<div className="page-header-action-group"><AdminDrawerComposer label="Nova proposta" title="Nova proposta" description="Valores, validade e histórico da negociação." icon={Plus}><ProposalForm deals={dealChoices} properties={propertyChoices}/></AdminDrawerComposer><AdminDrawerComposer label="Concluir venda" title="Concluir venda" description="Atualiza imóvel, CRM, comissão e dashboard." variant="secondary"><SaleForm deals={dealChoices} properties={propertyChoices} proposals={proposalChoices}/></AdminDrawerComposer></div>}/><AdminTabs tabs={[{id:"propostas",label:"Propostas",content:proposalList},{id:"vendas",label:"Vendas concluídas",content:saleList}]}/></div>;
}
