import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, CheckCircle2, Home, KeyRound, MapPin, Search, ShieldCheck } from "lucide-react";
import { PropertyCard } from "@/components/property-card";
import { publicProperties } from "@/lib/public-properties";
export const dynamic = "force-dynamic";

export default async function HomePage() { const properties = await publicProperties(); return <>
  <section className="hero"><Image src="https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=2000&q=90" alt="Casa contemporânea cercada por paisagismo" fill priority sizes="100vw"/><div className="hero-overlay"/><div className="shell hero-content"><div className="hero-kicker">Curadoria imobiliária em São Paulo</div><h1>O espaço certo muda<br/>a forma de <em>viver.</em></h1><p>Uma seleção cuidadosa de imóveis e acompanhamento próximo em cada decisão.</p><form action="/imoveis" className="hero-search"><label><span>Onde você quer morar?</span><div><MapPin/><input name="q" placeholder="Bairro ou cidade"/></div></label><label><span>Tipo de imóvel</span><select name="type"><option value="">Todos os tipos</option><option>Casa</option><option>Apartamento</option><option>Cobertura</option></select></label><label><span>Quartos</span><select name="bedrooms"><option value="">Qualquer</option><option value="2">2+</option><option value="3">3+</option><option value="4">4+</option></select></label><button aria-label="Buscar imóveis"><Search/></button></form></div></section>
  <section className="section shell"><div className="section-heading"><div><span className="eyebrow">Seleção Avan</span><h2>Imóveis que merecem<br/>ser vistos de perto</h2></div><Link className="text-link" href="/imoveis">Ver todos os imóveis <ArrowRight/></Link></div><div className="property-grid">{properties.slice(0,3).map((p)=><PropertyCard property={p} key={p.id}/>)}</div></section>
  <section className="statement"><div className="shell statement-grid"><div><span className="eyebrow eyebrow-light">Nosso jeito de trabalhar</span><h2>Menos pressa.<br/>Mais <em>critério.</em></h2></div><div className="benefits"><div><ShieldCheck/><h3>Informação clara</h3><p>Dados verificados, contexto de mercado e transparência do primeiro contato à assinatura.</p></div><div><KeyRound/><h3>Acompanhamento próximo</h3><p>Uma pessoa responsável por conduzir cada etapa e manter você informado.</p></div><div><CheckCircle2/><h3>Curadoria real</h3><p>Visitamos, avaliamos e selecionamos imóveis com potencial de fazer sentido para você.</p></div></div></div></section>
  <section className="section shell"><div className="section-heading"><div><span className="eyebrow">Explore por perfil</span><h2>Qual espaço combina<br/>com o seu momento?</h2></div></div><div className="category-grid"><Link href="/imoveis?type=Casa"><Home/><span>Casas</span><small>Arquitetura, privacidade e jardim</small></Link><Link href="/imoveis?type=Apartamento"><Building2/><span>Apartamentos</span><small>Localização e vida urbana</small></Link><Link href="/imoveis?type=Cobertura"><KeyRound/><span>Coberturas</span><small>Vista, amplitude e exclusividade</small></Link></div></section>
  <section className="newsletter"><div className="shell newsletter-inner"><div><span className="eyebrow eyebrow-light">Busca personalizada</span><h2>Receba imóveis alinhados ao que procura.</h2><p>Conte suas preferências e avisaremos quando uma nova oportunidade entrar no catálogo.</p></div><form><input type="email" placeholder="Seu melhor e-mail" aria-label="E-mail" required/><button className="button button-accent">Criar alerta <ArrowRight/></button></form></div></section>
  </> }
