"use client";
import { useActionState, useState } from "react";
import { saveProposal,saveSale } from "@/app/painel/propostas/actions";
import { DateInputField } from "./date-time-fields";
import { MoneyInput } from "./money-input";
type Choice={id:string;label:string};
const Feedback=({state}:{state:{ok:boolean;message:string}})=>state.message?<p className={state.ok?"form-success-inline":"admin-form-error"}>{state.message}</p>:null;
export function ProposalForm({deals,properties}:{deals:Choice[];properties:Choice[]}){const[state,action,pending]=useActionState(saveProposal,{ok:false,message:""});return <form action={action} className="entity-form operational-form"><label>Oportunidade<select name="dealId" required defaultValue=""><option value="">Selecione</option>{deals.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Imóvel<select name="propertyId" required defaultValue=""><option value="">Selecione</option>{properties.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Valor anunciado<MoneyInput name="advertised" required/></label><label>Valor ofertado<MoneyInput name="amount" required/></label><label>Contraproposta<MoneyInput name="counter"/></label><DateInputField name="validUntil" label="Validade da proposta" hint="Opcional. A proposta expira no fim deste dia."/><label>Status<select name="status" defaultValue="enviada"><option value="enviada">Enviada</option><option value="em_negociacao">Em negociação</option><option value="contraproposta">Contraproposta</option><option value="recusada">Recusada</option><option value="expirada">Expirada</option></select></label><label className="wide">Observações<textarea name="notes" rows={3}/></label><Feedback state={state}/><button className="admin-button primary" disabled={pending}>{pending?"Salvando…":"Salvar proposta"}</button></form>}
export function SaleForm({deals,properties,proposals,defaultDealId="",onSaved}:{deals:Choice[];properties:Choice[];proposals:Choice[];defaultDealId?:string;onSaved?:()=>void|Promise<void>}){const[state,setState]=useState({ok:false,message:""});const[pending,setPending]=useState(false);return <form action={async form=>{setPending(true);setState({ok:false,message:""});try{const result=await saveSale({ok:false,message:""},form);setState(result);if(result.ok)await onSaved?.();}finally{setPending(false);}}} className="entity-form operational-form">{defaultDealId?<input type="hidden" name="dealId" value={defaultDealId}/>:<label>Oportunidade<select name="dealId" required defaultValue=""><option value="">Selecione</option>{deals.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>}<label>Imóvel<select name="propertyId" required defaultValue=""><option value="">Selecione</option>{properties.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Proposta aceita <small>opcional</small><select name="proposalId" defaultValue=""><option value="">Venda direta, sem proposta vinculada</option>{proposals.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Valor anunciado<MoneyInput name="advertised" required/></label><label>Valor final<MoneyInput name="amount" required/></label><label>Comissão (%)<input name="commissionPercent" type="number" min="0" max="100" step="0.01" required/></label><DateInputField name="soldAt" label="Data da venda" required shortcuts={false}/><label className="wide">Observações<textarea name="notes" rows={3}/></label><Feedback state={state}/><button className="admin-button primary" disabled={pending}>{pending?"Concluindo…":"Concluir venda"}</button></form>}
