"use client";
import Link from "next/link";
import {CalendarClock,GripVertical} from "lucide-react";
import {memo,useEffect,useRef,useState,type ReactNode} from "react";
import {useRouter} from "next/navigation";
import {DndContext,DragOverlay,MouseSensor,TouchSensor,KeyboardSensor,useSensor,useSensors,useDroppable,closestCorners,type DragEndEvent} from "@dnd-kit/core";
import {SortableContext,useSortable,verticalListSortingStrategy,sortableKeyboardCoordinates} from "@dnd-kit/sortable";
import {CSS} from "@dnd-kit/utilities";
import {moveOpportunity} from "@/app/painel/crm/move";
import {dealChoices} from "@/app/painel/crm/actions";
import {saveSale} from "@/app/painel/propostas/actions";
import {placeCard} from "@/lib/kanban";
import {CrmDialog} from "./crm-dialog";
import {lossReasons,type DealChoices} from "./deal-editor";
import {MoneyField,SearchPicker,DatePicker} from "./crm-fields";
type Column={id:string;name:string;color:string;isWon:boolean;isLost:boolean};
type Card={id:string;title:string;clientId:string;client:string;phone:string;email:string|null;stageId:string;value:string;tags:string[];nextActionAt:string|null;nextActionType:string|null;nextActionNote:string|null;stageDays:number};
type Move={id:string;stageId:string;beforeId:string|null;fromStageId:string};
function CardContent({card}:{card:Card}){return <><h3>{card.client}</h3><p>{card.title}</p>{card.value!=="Valor não informado"?<strong>{card.value}</strong>:null}{card.tags.length?<div className="deal-card-top">{card.tags.slice(0,2).map(tag=><span key={tag}>{tag}</span>)}</div>:null}{card.nextActionAt?<small><CalendarClock/>{card.nextActionType||"Próxima ação"} · {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(card.nextActionAt))}</small>:null}<em>{card.stageDays} {card.stageDays===1?"dia":"dias"} nesta etapa</em></>;}
const SortableCard=memo(function SortableCard({card,columns,disabled,onOpen,onMove,onOrder}:{card:Card;columns:Column[];disabled:boolean;onOpen:(card:Card)=>void;onMove:(id:string,stageId:string)=>void;onOrder:(id:string,direction:number)=>void}){
 const{attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:card.id,disabled,data:{stageId:card.stageId}});
 return <article ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.25:1}} className="deal-card sortable-deal">
 <button type="button" className="deal-drag-handle" {...attributes} {...listeners} aria-label={`Arrastar oportunidade de ${card.client}`}><GripVertical size={16}/></button><button type="button" className="deal-open" onClick={()=>onOpen(card)}><CardContent card={card}/></button>
 <details className="deal-menu"><summary aria-label={`Ações de ${card.client}`}>•••</summary><div><label>Mover para<select aria-label={`Mover ${card.client} para`} disabled={disabled} value={card.stageId} onChange={e=>onMove(card.id,e.target.value)}>{columns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button type="button" disabled={disabled} onClick={()=>onOrder(card.id,-1)}>Subir na etapa</button><button type="button" disabled={disabled} onClick={()=>onOrder(card.id,1)}>Descer na etapa</button></div></details></article>;
});
function BoardColumn({column,count,hidden,children}:{column:Column;count:number;hidden:boolean;children:ReactNode}){const{setNodeRef,isOver}=useDroppable({id:column.id});return <section ref={setNodeRef} className={`kanban-column${hidden?" is-mobile-hidden":""}${isOver?" drop-target":""}`}><header><div><i style={{background:column.color}}/><strong>{column.name}</strong></div><span>{count}</span></header><div className="kanban-stack">{children}{!count?<p className="column-empty">Solte uma oportunidade aqui</p>:null}</div></section>;}
function ClosingSale({card,onClose,onSaved}:{card:Card;onClose:()=>void;onSaved:()=>void|Promise<void>}){
 const[choices,setChoices]=useState<DealChoices|null>(null);const[propertyId,setPropertyId]=useState("");const[date,setDate]=useState("");const[pending,setPending]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{let active=true;dealChoices().then(c=>{if(active)setChoices(c);}).catch(()=>{if(active)setError("Não foi possível carregar os imóveis.");});return()=>{active=false;};},[]);
 const property=choices?.properties.find(p=>p.id===propertyId);
 return <CrmDialog title="Concluir venda" description={`${card.client} · ${card.title}`} onClose={()=>{if(!pending)onClose();}}><form className="deal-editor" action={async form=>{setPending(true);setError("");try{const result=await saveSale({ok:false,message:""},form);if(result.ok)await onSaved();else setError(result.message);}catch{setError("Não foi possível concluir a venda. Tente novamente.");}finally{setPending(false);}}}><div className="crm-drawer-scroll"><input type="hidden" name="dealId" value={card.id}/><input type="hidden" name="proposalId" value=""/>{choices?<SearchPicker label="Imóvel vendido *" name="propertyId" value={propertyId?[propertyId]:[]} onChange={ids=>setPropertyId(ids[0]||"")} options={choices.properties.map(p=>({id:p.id,label:`${p.code} · ${p.title}`}))}/>:<p>Carregando imóveis…</p>}<div className="crm-form-grid" key={propertyId}><MoneyField name="advertised" label="Valor anunciado" initial={property?String(property.priceCents/100):""} required/><MoneyField name="amount" label="Valor final *" initial={property?String(property.priceCents/100):""} required/><label>Comissão (%)<input name="commissionPercent" type="number" min="0" max="100" step="0.01" required/></label><DatePicker value={date} onChange={setDate}/><input type="hidden" name="soldAt" value={date}/><label className="wide">Observações<textarea name="notes" maxLength={5000} rows={3}/></label></div>{error?<p role="alert">{error}</p>:null}</div><footer className="crm-drawer-actions"><button type="button" className="admin-button secondary" disabled={pending} onClick={onClose}>Cancelar</button><button className="admin-button primary" disabled={pending||!date||!propertyId}>{pending?"Concluindo…":"Confirmar venda"}</button></footer></form></CrmDialog>;
}
export function CrmBoard({columns,cards}:{columns:Column[];cards:Card[]}){
 const router=useRouter();const[source,setSource]=useState(cards);const[items,setItems]=useState(cards);if(cards!==source){setSource(cards);setItems(cards);}
 const[selectedStage,setSelectedStage]=useState(columns[0]?.id||"");const[active,setActive]=useState<Card|null>(null);const[dragging,setDragging]=useState<Card|null>(null);const[pending,setPending]=useState(false);const[confirmation,setConfirmation]=useState<Move|null>(null);const[notice,setNotice]=useState("");const[reason,setReason]=useState("");const boardRef=useRef<HTMLDivElement>(null);
 const sensors=useSensors(useSensor(MouseSensor,{activationConstraint:{distance:8}}),useSensor(TouchSensor,{activationConstraint:{delay:250,tolerance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
 useEffect(()=>{const node=boardRef.current;if(!node)return;const fit=()=>{node.style.setProperty("--board-height",`${Math.max(320,window.innerHeight-node.getBoundingClientRect().top-20)}px`);};fit();window.addEventListener("resize",fit);const observer=new ResizeObserver(fit);if(node.parentElement)observer.observe(node.parentElement);return()=>{window.removeEventListener("resize",fit);observer.disconnect();};},[]);
 async function persist(move:Move,lostReason?:string){const previous=items;setItems(placeCard(items,move.id,move.stageId,move.beforeId).map(c=>c.id===move.id&&move.stageId!==move.fromStageId?{...c,stageDays:0}:c));setPending(true);setNotice("");try{const result=await moveOpportunity({...move,lostReason});if(!result.ok){setItems(previous);setNotice(result.message);}else{setConfirmation(null);setNotice("Oportunidade atualizada.");router.refresh();}}catch{setItems(previous);setNotice("Não foi possível mover a oportunidade. Tente novamente.");}finally{setPending(false);}}
 function request(move:Move){if(pending)return;const target=columns.find(c=>c.id===move.stageId);if(move.stageId!==move.fromStageId&&(target?.isWon||target?.isLost)){setReason("");setConfirmation(move);}else void persist(move);}
 function move(id:string,stageId:string){const card=items.find(c=>c.id===id);if(card)request({id,stageId,fromStageId:card.stageId,beforeId:null});}
 function order(id:string,direction:number){const card=items.find(c=>c.id===id);if(!card)return;const siblings=items.filter(c=>c.stageId===card.stageId);const index=siblings.findIndex(c=>c.id===id);if(index+direction<0||index+direction>=siblings.length)return;request({id,stageId:card.stageId,fromStageId:card.stageId,beforeId:direction<0?siblings[index-1].id:siblings[index+2]?.id||null});}
 function drop(event:DragEndEvent){setDragging(null);const{id}=event.active;const over=event.over;if(!over||id===over.id)return;const card=items.find(c=>c.id===id);if(!card)return;const targetCard=items.find(c=>c.id===over.id);const stageId=targetCard?.stageId||String(over.id);let beforeId=targetCard?.id||null;if(targetCard&&card.stageId===stageId){const siblings=items.filter(c=>c.stageId===stageId);if(siblings.indexOf(card)<siblings.indexOf(targetCard))beforeId=siblings[siblings.indexOf(targetCard)+1]?.id||null;}request({id:String(id),stageId,beforeId,fromStageId:card.stageId});}
 const target=columns.find(c=>c.id===confirmation?.stageId);const closing=items.find(c=>c.id===confirmation?.id);
 return <><p className="crm-board-notice" role="status" aria-live="polite">{notice||"Arraste pela alça ⋮⋮ ou use o menu do card para mover e ordenar."}</p><label className="crm-stage-picker">Etapa<select value={selectedStage} onChange={e=>setSelectedStage(e.target.value)}>{columns.map(c=><option key={c.id} value={c.id}>{c.name} ({items.filter(i=>i.stageId===c.id).length})</option>)}</select></label>
 <DndContext sensors={sensors} collisionDetection={closestCorners} onDragStart={e=>setDragging(items.find(c=>c.id===e.active.id)||null)} onDragEnd={drop} onDragCancel={()=>setDragging(null)} accessibility={{announcements:{onDragStart:({active})=>`Oportunidade de ${items.find(c=>c.id===active.id)?.client||"cliente"} selecionada para mover.`,onDragOver:({over})=>over?`Destino: ${columns.find(c=>c.id===(items.find(i=>i.id===over.id)?.stageId||over.id))?.name||"etapa"}.`:"Fora de uma área de destino.",onDragEnd:()=> "Arraste encerrado. Confira a atualização ou a confirmação solicitada.",onDragCancel:()=> "Movimentação cancelada."},screenReaderInstructions:{draggable:"Pressione espaço para arrastar, use as setas para mover e espaço para soltar. Escape cancela."}}}><div className="kanban crm-operational-board" ref={boardRef} aria-busy={pending}>{columns.map(c=>{const rows=items.filter(i=>i.stageId===c.id);return <BoardColumn key={c.id} column={c} count={rows.length} hidden={selectedStage!==c.id}><SortableContext items={rows.map(r=>r.id)} strategy={verticalListSortingStrategy}>{rows.map(card=><SortableCard key={card.id} card={card} columns={columns} disabled={pending} onOpen={setActive} onMove={move} onOrder={order}/>)}</SortableContext></BoardColumn>;})}</div><DragOverlay>{dragging?<div className="deal-card deal-drag-preview"><CardContent card={dragging}/></div>:null}</DragOverlay></DndContext>
 {active?<CrmDialog title={active.client} description="Ficha rápida da oportunidade" onClose={()=>setActive(null)}><div className="crm-drawer-scroll client-summary"><section><h3>Oportunidade</h3><strong>{active.title}</strong><p>{active.value}</p></section><section><h3>Contato</h3><a href={`tel:${active.phone}`}>{active.phone}</a>{active.email?<a href={`mailto:${active.email}`}>{active.email}</a>:null}</section><section><h3>Próxima ação</h3><p>{active.nextActionType||"Não definida"}</p>{active.nextActionNote?<p>{active.nextActionNote}</p>:null}{active.nextActionAt?<time>{new Date(active.nextActionAt).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}</time>:null}</section></div><footer className="crm-drawer-actions"><Link className="admin-button secondary" href={`/painel/crm?view=clientes&cliente=${active.clientId}`}>Ficha do cliente</Link><Link className="admin-button primary" href={`/painel/crm/${active.id}`}>Editar oportunidade</Link></footer></CrmDialog>:null}
 {confirmation&&target?.isLost?<CrmDialog title="Motivo da perda" description="Registre o motivo antes de mover para Perdido." compact onClose={()=>{if(!pending)setConfirmation(null);}}><form className="deal-editor" action={()=>persist(confirmation,reason)}><div className="crm-drawer-scroll"><label>Motivo da perda *<input list="board-loss-reasons" required value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/><datalist id="board-loss-reasons">{lossReasons.map(r=><option key={r}>{r}</option>)}</datalist></label>{notice?<p role="alert">{notice}</p>:null}</div><footer className="crm-drawer-actions"><button type="button" className="admin-button secondary" disabled={pending} onClick={()=>setConfirmation(null)}>Cancelar</button><button className="admin-button primary" disabled={pending||!reason.trim()}>Confirmar perda</button></footer></form></CrmDialog>:null}
 {confirmation&&target?.isWon&&closing?<ClosingSale card={closing} onClose={()=>setConfirmation(null)} onSaved={async()=>{setConfirmation(null);setItems(placeCard(items,closing.id,target.id,confirmation.beforeId));setPending(true);try{const result=await moveOpportunity({...confirmation,fromStageId:target.id});setNotice(result.ok?"Venda concluída com sucesso.":"Venda concluída. Atualize o quadro para conferir a ordenação.");}catch{setNotice("Venda concluída. Atualize o quadro para conferir a ordenação.");}finally{setPending(false);router.refresh();}}}/>:null}</>;
}
