"use client";
import {useId,useState} from "react";
import Image from "next/image";
import {CalendarDays,ChevronLeft,ChevronRight,Search,X} from "lucide-react";
export function MoneyField({name,label,initial="",required=false}:{name:string;label:string;initial?:string;required?:boolean}){
 const[cents,setCents]=useState(initial?String(Math.round(Number(initial)*100)):"");
 return <label>{label}<input inputMode="decimal" required={required} value={cents?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(cents)/100):""} placeholder="R$ 0,00" onChange={e=>setCents(e.target.value.replace(/\D/g,"").slice(0,10))}/><input type="hidden" name={name} value={cents?(Number(cents)/100).toFixed(2):""}/></label>;
}
type Option={id:string;label:string;detail?:string;image?:string|null};
export function SearchPicker({label,name,options,value,onChange,multiple=false,disabled=false}:{label:string;name:string;options:Option[];value:string[];onChange:(ids:string[])=>void;multiple?:boolean;disabled?:boolean}){
 const[search,setSearch]=useState("");const[open,setOpen]=useState(false);const id=useId();
 const matches=options.filter(o=>`${o.label} ${o.detail||""}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))).slice(0,40);
 return <div className="crm-search-picker"><label htmlFor={id}>{label}</label>{value.map(v=><input key={v} type="hidden" name={name} value={v}/>)}{!multiple&&!value.length?<input type="hidden" name={name} value=""/>:null}<div className="crm-selected-tags">{value.map(v=>{const o=options.find(o=>o.id===v);return o?<span key={v}>{o.label}{!disabled?<button type="button" aria-label={`Remover ${o.label}`} onClick={()=>onChange(value.filter(x=>x!==v))}><X size={12}/></button>:null}</span>:null;})}</div>
 {!disabled?<><div className="crm-picker-search"><Search size={16}/><input id={id} value={search} placeholder={multiple?"Buscar imóvel…":"Buscar cliente…"} role="combobox" aria-haspopup="dialog" aria-expanded={open} aria-controls={`${id}-options`} onFocus={()=>setOpen(true)} onChange={e=>{setSearch(e.target.value);setOpen(true);}} onKeyDown={e=>{if(e.key==="Escape"){e.stopPropagation();setOpen(false);}if(e.key==="ArrowDown"){e.preventDefault();document.getElementById(`${id}-options`)?.querySelector<HTMLButtonElement>("button")?.focus();}}}/></div>{open?<div id={`${id}-options`} className="crm-picker-options" role="dialog" aria-label={label}>{matches.map(o=><button type="button" key={o.id} aria-pressed={value.includes(o.id)} onClick={()=>{onChange(multiple?(value.includes(o.id)?value.filter(v=>v!==o.id):[...value,o.id]):[o.id]);setSearch("");if(!multiple)setOpen(false);}}>{o.image?<Image unoptimized src={o.image} alt="" width={48} height={40}/>:null}<span><strong>{o.label}</strong><small>{o.detail}</small></span><span>{value.includes(o.id)?"✓":"+"}</span></button>)}{!matches.length?<p>Nenhum resultado encontrado.</p>:null}<button type="button" onClick={()=>setOpen(false)}>Concluir seleção</button></div>:null}</>:null}</div>;
}
function dateKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
export function DatePicker({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const[open,setOpen]=useState(false);const[month,setMonth]=useState(()=>new Date(`${value||dateKey(new Date())}T12:00:00`));const first=new Date(month.getFullYear(),month.getMonth(),1);const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const choose=(v:string)=>{onChange(v);setOpen(false);};
 return <div className="crm-date-picker"><span>Data</span><button type="button" className="crm-date-trigger" aria-label="Escolher data" aria-expanded={open} onClick={()=>setOpen(!open)}>{value?value.split("-").reverse().join("/"):"DD/MM/AAAA"}<CalendarDays size={16}/></button>{open?<div className="crm-calendar"><header><button type="button" aria-label="Mês anterior" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><strong>{month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</strong><button type="button" aria-label="Próximo mês" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></header><div className="crm-calendar-grid">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(d=><small key={d}>{d}</small>)}{Array.from({length:first.getDay()},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const key=dateKey(new Date(month.getFullYear(),month.getMonth(),i+1));return <button type="button" aria-label={key.split("-").reverse().join("/")} aria-pressed={value===key} key={key} onClick={()=>choose(key)}>{i+1}</button>;})}</div><label>Digitar data<input type="date" value={value} onChange={e=>choose(e.target.value)}/></label></div>:null}<div className="crm-date-shortcuts">{[[0,"Hoje"],[1,"Amanhã"],[2,"+ 2 dias"],[7,"Próxima semana"]].map(([days,label])=><button type="button" key={days} onClick={()=>{const d=new Date();d.setDate(d.getDate()+Number(days));choose(dateKey(d));}}>{label}</button>)}</div></div>;
}
