"use client";
import {useState,useId} from "react";
import {useRouter} from "next/navigation";
import {saveDeal,dealChoices} from "@/app/painel/crm/actions";
import {DatePicker,MoneyField,SearchPicker} from "./crm-fields";
import {CrmDialog} from "./crm-dialog";
import {ClientForm} from "./crm-workspace";
export type DealChoices=Awaited<ReturnType<typeof dealChoices>>;
export const lossReasons=["Preço","Localização","Sem retorno","Desistiu","Comprou outro imóvel","Comprou com concorrente","Financiamento","Outro"];
const actionTypes=["Ligar","WhatsApp","Enviar imóveis","Confirmar visita","Retornar cliente","Cobrar proposta","Outro"];
export function DealEditor({choices:base,initial={},selected=[],onSaved,onCancel}:{choices:DealChoices;initial?:Record<string,string>;selected?:string[];onSaved?:()=>void;onCancel?:()=>void}){
 const router=useRouter();const[choices,setChoices]=useState(base);const[clientId,setClientId]=useState(initial.clientId||"");const client=choices.clients.find(c=>c.id===clientId);const[stageId,setStageId]=useState(initial.stageId||choices.stages.find(s=>!s.isWon&&!s.isLost)?.id||"");
 const[type,setType]=useState(initial.nextActionType||"");const[date,setDate]=useState(initial.nextActionAt?new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Sao_Paulo"}).format(new Date(initial.nextActionAt)):"");const[time,setTime]=useState(initial.nextActionAt?new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"America/Sao_Paulo"}).format(new Date(initial.nextActionAt)):"09:00");
 const[properties,setProperties]=useState(selected);const[addingClient,setAddingClient]=useState(false);const[pending,setPending]=useState(false);const[error,setError]=useState("");const timeId=useId();
 async function submit(form:FormData){setPending(true);setError("");try{form.set("returnToBoard","1");const result=await saveDeal({ok:false,message:""},form);if(result.ok){if(onSaved)onSaved();else router.push("/painel/crm?criado=1");router.refresh();}else setError(result.message);}catch{setError("Não foi possível salvar. Verifique a conexão e tente novamente.");}finally{setPending(false);}}
 return <><form action={submit} className="deal-editor"><input type="hidden" name="id" value={initial.id||""}/><div className="crm-drawer-scroll">
 <section className="crm-form-section"><header><span>Dados da oportunidade</span><p>Defina o cliente e o negócio que você está acompanhando.</p></header><div className="crm-form-grid"><div><SearchPicker label="Cliente *" name="clientId" options={choices.clients.map(c=>({id:c.id,label:c.name,detail:c.phone}))} value={clientId?[clientId]:[]} onChange={ids=>setClientId(ids[0]||"")} disabled={!!initial.id}/>{!initial.id?<button type="button" className="crm-text-button" onClick={()=>setAddingClient(true)}>+ Novo cliente</button>:null}</div><label>Título *<input name="title" required minLength={3} maxLength={180} defaultValue={initial.title||""} placeholder="Ex.: Casa com quintal no Centro"/></label><label>Etapa<select name="stageId" value={stageId} onChange={e=>setStageId(e.target.value)}>{choices.stages.map(s=><option key={s.id} value={s.id} disabled={s.isWon&&initial.stageId!==s.id}>{s.name}{s.isWon&&initial.stageId!==s.id?" — concluir venda pelo Kanban":""}</option>)}</select></label><MoneyField name="amount" label="Valor estimado" initial={initial.amount}/></div></section>
 <section className="crm-form-section"><header><span>Próximo contato</span><p>Organize a próxima ação deste atendimento.</p></header><label>Tipo da próxima ação<select name="nextActionType" value={type} onChange={e=>setType(e.target.value)}><option value="">Sem próxima ação</option>{[...new Set([...actionTypes,...(initial.nextActionType?[initial.nextActionType]:[])])].map(t=><option key={t}>{t}</option>)}</select></label><div className="crm-action-chips">{actionTypes.slice(0,4).map(t=><button type="button" aria-pressed={type===t} key={t} onClick={()=>setType(type===t?"":t)}>{t}</button>)}</div>{type?<div className="crm-form-grid"><DatePicker value={date} onChange={setDate}/><label>Horário <small>Brasília</small><input type="time" required value={time} onChange={e=>setTime(e.target.value)} list={timeId}/><datalist id={timeId}>{Array.from({length:21},(_,i)=>{const t=`${String(8+Math.floor(i/2)).padStart(2,"0")}:${i%2?"30":"00"}`;return <option key={t} value={t}/>;})}</datalist></label><label className="wide">Observação da próxima ação<input name="nextActionNote" maxLength={500} defaultValue={initial.nextActionNote||""} placeholder="Contexto curto para o próximo contato"/></label></div>:<input type="hidden" name="nextActionNote" value=""/>}<input type="hidden" name="nextActionAt" value={type&&date&&time?`${date}T${time}:00-03:00`:""}/></section>
 <section className="crm-form-section"><header><span>Imóveis <small>opcional</small></span></header><SearchPicker label="Imóveis de interesse (opcional)" name="propertyIds" options={choices.properties.map(p=>({id:p.id,label:`${p.code} · ${p.title}`,detail:`${new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(p.priceCents/100)} · ${p.neighborhood} · ${p.city}`,image:p.photoId?`/api/property-photos/${p.photoId}`:null}))} value={properties} onChange={setProperties} multiple/></section>
 <section className="crm-form-section"><header><span>Informações internas</span></header><div className="crm-form-grid">{choices.team.length?<label>Responsável pelo cliente<select name="assignedTo" key={clientId} defaultValue={client?.assignedTo||""}><option value="">Sem responsável</option>{choices.team.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>:<input type="hidden" name="assignedTo" value={client?.assignedTo||""}/>}{choices.stages.find(s=>s.id===stageId)?.isLost?<label>Motivo da perda *<input required name="lostReason" list="crm-loss-reasons" maxLength={2000} defaultValue={initial.lostReason||""}/><datalist id="crm-loss-reasons">{lossReasons.map(reason=><option key={reason}>{reason}</option>)}</datalist></label>:<input type="hidden" name="lostReason" value=""/>}<label className="wide">Nota<textarea name="note" rows={3} maxLength={10000} placeholder="Adicione uma observação sobre esta oportunidade…"/></label></div></section>{error?<p role="alert" className="crm-form-message error">{error}</p>:null}
 </div><footer className="crm-drawer-actions"><button type="button" disabled={pending} className="admin-button secondary" onClick={()=>onCancel?onCancel():router.push("/painel/crm")}>Cancelar</button><button className="admin-button primary" disabled={pending||!clientId||!!(type&&!date)}>{pending?"Salvando…":initial.id?"Salvar alterações":"Criar oportunidade"}</button>{type&&!date?<small>Escolha a data do contato.</small>:null}</footer></form>{addingClient?<CrmDialog title="Novo cliente" onClose={()=>setAddingClient(false)}><ClientForm onClose={()=>setAddingClient(false)} onSaved={async id=>{const updated=await dealChoices();setChoices(updated);setClientId(id);setAddingClient(false);}}/></CrmDialog>:null}</>;
}
