"use client";
import { useState } from "react";
import Link from "next/link";
import { pageHref, type Query } from "@/lib/list-query";
export function ListFilters({scope,userId,query,children}:{scope:string;userId:string;query:Query;children?:React.ReactNode}){
 const [saved,setSaved]=useState<{name:string;query:string}[]>([]);const [name,setName]=useState("");const [message,setMessage]=useState("");const key=`avanca:filters:v1:${userId}:${scope}`;
 function load(){try{const rows=JSON.parse(localStorage.getItem(key)||"[]");setSaved(Array.isArray(rows)?rows.filter(x=>typeof x.name==="string"&&typeof x.query==="string"&&x.query.startsWith("?")).slice(0,20):[]);}catch{setMessage("Não foi possível ler os filtros salvos.");}}
 function save(){if(!name.trim())return;const qs=new URLSearchParams();Object.entries(query).forEach(([k,v])=>{if(typeof v==="string"&&k!=="page")qs.set(k,v);});try{const rows=JSON.parse(localStorage.getItem(key)||"[]");const next=[{name:name.trim().slice(0,60),query:"?"+qs.toString()},...(Array.isArray(rows)?rows:[]).filter(x=>x.name!==name.trim())].slice(0,20);localStorage.setItem(key,JSON.stringify(next));setSaved(next);setName("");setMessage("Filtro salvo neste navegador.");}catch{setMessage("O navegador não permitiu salvar o filtro.");}}
 return <section className="list-tools"><form method="get" className="filter-row"><label>Buscar<input name="q" defaultValue={String(query.q||"")} placeholder="Nome, código ou contato"/></label>{children}<button className="admin-button primary">Filtrar</button><Link className="admin-button secondary" href={`/painel/${scope}`}>Limpar</Link></form><details onToggle={e=>{if(e.currentTarget.open)load();}}><summary>Filtros salvos</summary><div className="filter-row"><label>Nome do filtro<input value={name} onChange={e=>setName(e.target.value)} maxLength={60}/></label><button type="button" className="admin-button secondary" onClick={save}>Salvar filtros atuais</button>{saved.map((s,i)=><Link className="text-action" key={i} href={s.query}>{s.name}</Link>)}</div>{message?<p role="status">{message}</p>:null}</details></section>;
}
export function Pagination({query,page,total,size=20}:{query:Query;page:number;total:number;size?:number}){const pages=Math.max(1,Math.ceil(total/size));return <nav className="pagination" aria-label="Paginação"><span>{total} registros · Página {page} de {pages}</span>{page>1?<Link className="admin-button secondary" href={pageHref(query,page-1)}>Anterior</Link>:null}{page<pages?<Link className="admin-button secondary" href={pageHref(query,page+1)}>Próxima</Link>:null}</nav>;}
