"use client";
import { useState } from "react";
import { modules, moduleLabels, type Module } from "@/lib/permissions";
import { BrandLogosEditor } from "@/components/brand-logos-editor";
import type { BrandLogoEntry } from "@/lib/branding";
const steps=["Empresa","Identidade","Site","Recursos","Administrador","Revisão"] as const;
type Draft={name:string;slug:string;phone:string;whatsapp:string;email:string;logos:BrandLogoEntry[];favicon:string;primaryColor:string;secondaryColor:string;accentColor:string;plan:"starter"|"pro"|"max"|"custom";modules:Module[];adminName:string;adminEmail:string};
const initial:Draft={name:"",slug:"",phone:"",whatsapp:"",email:"",logos:[{id:"primary",name:"Marca principal",logoLight:"",logoDark:""}],favicon:"",primaryColor:"#2563eb",secondaryColor:"#111827",accentColor:"#d6a84f",plan:"starter",modules:["dashboard","imoveis","clientes","crm"],adminName:"",adminEmail:""};
export function TenantWizard(){
 const[step,setStep]=useState(0);const[draft,setDraft]=useState(initial);const[busy,setBusy]=useState(false);const[result,setResult]=useState<{error?:string;inviteUrl?:string}|null>(null);
 const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft((current)=>({...current,[key]:value}));
 const toggle=(module:Module)=>set("modules",draft.modules.includes(module)?draft.modules.filter((item)=>item!==module):[...draft.modules,module]);
 async function create(){setBusy(true);setResult(null);try{const response=await fetch("/api/superadmin/tenants",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:draft.name,slug:draft.slug,phone:draft.phone,whatsapp:draft.whatsapp,email:draft.email,plan:draft.plan,modules:draft.modules,branding:{logos:draft.logos,logoLight:draft.logos[0]?.logoLight,logoDark:draft.logos[0]?.logoDark,favicon:draft.favicon},site:{primaryColor:draft.primaryColor,secondaryColor:draft.secondaryColor,accentColor:draft.accentColor,title:draft.name},admin:{name:draft.adminName,email:draft.adminEmail}})});const data=await response.json();setResult(response.ok?{inviteUrl:data.inviteUrl}:{error:data.error});}catch{setResult({error:"Não foi possível conectar."})}setBusy(false)}
 return <section className="section-card"><ol className="admin-tabs" aria-label="Etapas">{steps.map((label,index)=><li key={label} aria-current={index===step?"step":undefined}>{index+1}. {label}</li>)}</ol>
  <div className="form-grid">
   {step===0?<><label>Nome<input value={draft.name} onChange={(e)=>set("name",e.target.value)}/></label><label>Slug<input value={draft.slug} onChange={(e)=>set("slug",e.target.value)}/></label><label>Telefone<input value={draft.phone} onChange={(e)=>set("phone",e.target.value)}/></label><label>WhatsApp<input value={draft.whatsapp} onChange={(e)=>set("whatsapp",e.target.value)}/></label><label>E-mail<input type="email" value={draft.email} onChange={(e)=>set("email",e.target.value)}/></label></>:null}
   {step===1?<><BrandLogosEditor initialLogos={draft.logos} onChange={(logos)=>set("logos",logos)}/><label className="wide">Favicon<input type="url" value={draft.favicon} onChange={(e)=>set("favicon",e.target.value)}/></label></>:null}
   {step===2?<><label>Cor principal<input type="color" value={draft.primaryColor} onChange={(e)=>set("primaryColor",e.target.value)}/></label><label>Cor secundária<input type="color" value={draft.secondaryColor} onChange={(e)=>set("secondaryColor",e.target.value)}/></label><label>Cor de destaque<input type="color" value={draft.accentColor} onChange={(e)=>set("accentColor",e.target.value)}/></label></>:null}
   {step===3?<><label>Plano<select value={draft.plan} onChange={(e)=>set("plan",e.target.value as Draft["plan"])}><option value="starter">Starter</option><option value="pro">Pro</option><option value="max">Max</option><option value="custom">Custom</option></select></label><fieldset><legend>Módulos</legend>{modules.map((module)=><label key={module}><input type="checkbox" checked={draft.modules.includes(module)} onChange={()=>toggle(module)}/>{moduleLabels[module]}</label>)}</fieldset></>:null}
   {step===4?<><label>Nome do administrador<input value={draft.adminName} onChange={(e)=>set("adminName",e.target.value)}/></label><label>E-mail do administrador<input type="email" value={draft.adminEmail} onChange={(e)=>set("adminEmail",e.target.value)}/></label></>:null}
   {step===5?<div><h2>Revisão</h2><p><strong>{draft.name}</strong> · /empresa/{draft.slug}</p><p>{draft.plan} · {draft.modules.map((item)=>moduleLabels[item]).join(", ")}</p><p>Administrador: {draft.adminName} ({draft.adminEmail})</p></div>:null}
  </div>
  {result?.error?<p role="alert" className="login-error">{result.error}</p>:null}{result?.inviteUrl?<div role="status"><p>Empresa criada em configuração. Compartilhe o link de convite por canal seguro:</p><output>{result.inviteUrl}</output></div>:null}
  <div className="form-actions"><button type="button" disabled={step===0||busy} onClick={()=>setStep((value)=>Math.max(0,value-1))}>Voltar</button>{step<5?<button type="button" onClick={()=>setStep((value)=>Math.min(5,value+1))}>Continuar</button>:<button type="button" disabled={busy} onClick={create}>{busy?"Criando...":"Criar empresa"}</button>}</div>
 </section>
}
