import { NextResponse } from "next/server";
import { headers } from "next/headers";
import { z } from "zod";
import { getDb } from "@/db";
import { activities, clients, dealProperties, deals, stages } from "@/db/schema";
import { checkRateLimit } from "@/lib/rate-limit";

const schema=z.object({name:z.string().trim().min(2).max(160),phone:z.string().trim().min(8).max(30),email:z.email().max(254),message:z.string().trim().max(1200).optional(),propertyId:z.uuid(),consent:z.literal("true")});
export async function POST(request:Request){try{const forwarded=(await headers()).get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";if(!await checkRateLimit(`lead:${forwarded}`,5,60*60*1000))return NextResponse.json({error:"Muitas solicitações. Tente novamente mais tarde."},{status:429});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Revise os campos informados."},{status:400});const db=getDb();const [client]=await db.insert(clients).values({name:parsed.data.name,phone:parsed.data.phone,email:parsed.data.email.toLowerCase(),origin:"site",lgpdConsentAt:new Date()}).returning({id:clients.id});const [stage]=await db.select({id:stages.id}).from(stages).orderBy(stages.position).limit(1);if(stage){const [deal]=await db.insert(deals).values({clientId:client.id,stageId:stage.id,title:`Interesse pelo site — ${parsed.data.name}`,position:"1000",tags:["site","novo-lead"]}).returning({id:deals.id});await Promise.all([db.insert(dealProperties).values({dealId:deal.id,propertyId:parsed.data.propertyId}),db.insert(activities).values({dealId:deal.id,clientId:client.id,type:"lead_recebido",description:parsed.data.message||"Interesse enviado pelo site"})]);}return NextResponse.json({message:"Recebemos seus dados. Nossa equipe entrará em contato."},{status:201});}catch(error){console.error("lead_create_failed",error instanceof Error?error.message:"unknown");return NextResponse.json({error:"Serviço temporariamente indisponível."},{status:503})}}
